apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app: agent-sandbox-controller
  name: agent-sandbox-controller
  namespace: agent-sandbox-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: agent-sandbox-controller
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: agent-sandbox-controller
subjects:
- kind: ServiceAccount
  name: agent-sandbox-controller
  namespace: agent-sandbox-system
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: agent-sandbox-controller
  name: agent-sandbox-controller
  namespace: agent-sandbox-system
spec:
  ports:
  - name: metrics
    port: 8080
    protocol: TCP
    targetPort: metrics
  selector:
    app: agent-sandbox-controller
