runtime: python39

handlers:
  - url: /
    static_files: public/index.html
    upload: public/*
    require_matching_file: true
    secure: always
    redirect_http_response_code: 301

  - url: /(.*)
    static_files: public/\1/index.html
    upload: public/*
    require_matching_file: true
    secure: always
    redirect_http_response_code: 301
  
  - url: /(.*)/
    static_files: public/\1/index.html
    upload: public/*
    require_matching_file: true
    secure: always
    redirect_http_response_code: 301

  - url: /
    static_dir: public/
    require_matching_file: true
    secure: always
    redirect_http_response_code: 301
