// Copyright 2026 The Kubernetes Authors.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by informer-gen. DO NOT EDIT.

package v1alpha1

import (
	context "context"
	time "time"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
	versioned "sigs.k8s.io/agent-sandbox/clients/k8s/extensions/clientset/versioned"
	internalinterfaces "sigs.k8s.io/agent-sandbox/clients/k8s/extensions/informers/externalversions/internalinterfaces"
	apiv1alpha1 "sigs.k8s.io/agent-sandbox/clients/k8s/extensions/listers/api/v1alpha1"
	extensionsapiv1alpha1 "sigs.k8s.io/agent-sandbox/extensions/api/v1alpha1"
)

// SandboxTemplateInformer provides access to a shared informer and lister for
// SandboxTemplates.
type SandboxTemplateInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() apiv1alpha1.SandboxTemplateLister
}

type sandboxTemplateInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
	namespace        string
}

// NewSandboxTemplateInformer constructs a new informer for SandboxTemplate type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewSandboxTemplateInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredSandboxTemplateInformer(client, namespace, resyncPeriod, indexers, nil)
}

// NewFilteredSandboxTemplateInformer constructs a new informer for SandboxTemplate type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredSandboxTemplateInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.ExtensionsV1alpha1().SandboxTemplates(namespace).List(context.Background(), options)
			},
			WatchFunc: func(options v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.ExtensionsV1alpha1().SandboxTemplates(namespace).Watch(context.Background(), options)
			},
			ListWithContextFunc: func(ctx context.Context, options v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.ExtensionsV1alpha1().SandboxTemplates(namespace).List(ctx, options)
			},
			WatchFuncWithContext: func(ctx context.Context, options v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.ExtensionsV1alpha1().SandboxTemplates(namespace).Watch(ctx, options)
			},
		},
		&extensionsapiv1alpha1.SandboxTemplate{},
		resyncPeriod,
		indexers,
	)
}

func (f *sandboxTemplateInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredSandboxTemplateInformer(client, f.namespace, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *sandboxTemplateInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&extensionsapiv1alpha1.SandboxTemplate{}, f.defaultInformer)
}

func (f *sandboxTemplateInformer) Lister() apiv1alpha1.SandboxTemplateLister {
	return apiv1alpha1.NewSandboxTemplateLister(f.Informer().GetIndexer())
}
