# Copyright 2026 The Kubernetes Authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from process.v1 import process_pb2 as process_dot_v1_dot_process__pb2


class ProcessServiceStub:
    """ProcessService manages process execution, lifecycle, signals, and interactive terminals (PTY).
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Start = channel.unary_stream(
                '/process.v1.ProcessService/Start',
                request_serializer=process_dot_v1_dot_process__pb2.StartRequest.SerializeToString,
                response_deserializer=process_dot_v1_dot_process__pb2.StartResponse.FromString,
                _registered_method=True)
        self.Execute = channel.unary_unary(
                '/process.v1.ProcessService/Execute',
                request_serializer=process_dot_v1_dot_process__pb2.ExecuteRequest.SerializeToString,
                response_deserializer=process_dot_v1_dot_process__pb2.ExecuteResponse.FromString,
                _registered_method=True)
        self.WriteStdin = channel.unary_unary(
                '/process.v1.ProcessService/WriteStdin',
                request_serializer=process_dot_v1_dot_process__pb2.WriteStdinRequest.SerializeToString,
                response_deserializer=process_dot_v1_dot_process__pb2.WriteStdinResponse.FromString,
                _registered_method=True)
        self.SendSignal = channel.unary_unary(
                '/process.v1.ProcessService/SendSignal',
                request_serializer=process_dot_v1_dot_process__pb2.SendSignalRequest.SerializeToString,
                response_deserializer=process_dot_v1_dot_process__pb2.SendSignalResponse.FromString,
                _registered_method=True)
        self.ResizeTTY = channel.unary_unary(
                '/process.v1.ProcessService/ResizeTTY',
                request_serializer=process_dot_v1_dot_process__pb2.ResizeTTYRequest.SerializeToString,
                response_deserializer=process_dot_v1_dot_process__pb2.ResizeTTYResponse.FromString,
                _registered_method=True)


class ProcessServiceServicer:
    """ProcessService manages process execution, lifecycle, signals, and interactive terminals (PTY).
    """

    def Start(self, request, context):
        """Start runs a command and streams its stdout/stderr events in real time.
        Use for long-running or interactive processes (shells, servers, interactive commands).
        The stream remains open until the process terminates and sends an ExitEvent.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Execute(self, request, context):
        """Execute runs a short-lived command synchronously to completion and returns stdout,
        stderr, and the exit code atomically. Use when real-time streaming is not required.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def WriteStdin(self, request, context):
        """WriteStdin sends standard input bytes or EOF to an active running process.
        Note: Any stdout/stderr produced by the process in response to this input
        flows continuously through the active Start stream rather than WriteStdinResponse.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SendSignal(self, request, context):
        """SendSignal delivers a POSIX signal to a running process group.
        Errors (e.g., process not found or permission denied) are surfaced via standard
        gRPC status codes (NOT_FOUND, PERMISSION_DENIED).
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ResizeTTY(self, request, context):
        """ResizeTTY dynamically resizes the pseudo-terminal window of a running process.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ProcessServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Start': grpc.unary_stream_rpc_method_handler(
                    servicer.Start,
                    request_deserializer=process_dot_v1_dot_process__pb2.StartRequest.FromString,
                    response_serializer=process_dot_v1_dot_process__pb2.StartResponse.SerializeToString,
            ),
            'Execute': grpc.unary_unary_rpc_method_handler(
                    servicer.Execute,
                    request_deserializer=process_dot_v1_dot_process__pb2.ExecuteRequest.FromString,
                    response_serializer=process_dot_v1_dot_process__pb2.ExecuteResponse.SerializeToString,
            ),
            'WriteStdin': grpc.unary_unary_rpc_method_handler(
                    servicer.WriteStdin,
                    request_deserializer=process_dot_v1_dot_process__pb2.WriteStdinRequest.FromString,
                    response_serializer=process_dot_v1_dot_process__pb2.WriteStdinResponse.SerializeToString,
            ),
            'SendSignal': grpc.unary_unary_rpc_method_handler(
                    servicer.SendSignal,
                    request_deserializer=process_dot_v1_dot_process__pb2.SendSignalRequest.FromString,
                    response_serializer=process_dot_v1_dot_process__pb2.SendSignalResponse.SerializeToString,
            ),
            'ResizeTTY': grpc.unary_unary_rpc_method_handler(
                    servicer.ResizeTTY,
                    request_deserializer=process_dot_v1_dot_process__pb2.ResizeTTYRequest.FromString,
                    response_serializer=process_dot_v1_dot_process__pb2.ResizeTTYResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'process.v1.ProcessService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('process.v1.ProcessService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ProcessService:
    """ProcessService manages process execution, lifecycle, signals, and interactive terminals (PTY).
    """

    @staticmethod
    def Start(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/process.v1.ProcessService/Start',
            process_dot_v1_dot_process__pb2.StartRequest.SerializeToString,
            process_dot_v1_dot_process__pb2.StartResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Execute(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/process.v1.ProcessService/Execute',
            process_dot_v1_dot_process__pb2.ExecuteRequest.SerializeToString,
            process_dot_v1_dot_process__pb2.ExecuteResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def WriteStdin(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/process.v1.ProcessService/WriteStdin',
            process_dot_v1_dot_process__pb2.WriteStdinRequest.SerializeToString,
            process_dot_v1_dot_process__pb2.WriteStdinResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SendSignal(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/process.v1.ProcessService/SendSignal',
            process_dot_v1_dot_process__pb2.SendSignalRequest.SerializeToString,
            process_dot_v1_dot_process__pb2.SendSignalResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ResizeTTY(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/process.v1.ProcessService/ResizeTTY',
            process_dot_v1_dot_process__pb2.ResizeTTYRequest.SerializeToString,
            process_dot_v1_dot_process__pb2.ResizeTTYResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
