steps:
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'build', '-t', 'us-docker.pkg.dev/<PROJECT_ID>/<REGISTRY_NAME>/gymnasium-env:1.0.0', '.' ]
images:
- 'us-docker.pkg.dev/<PROJECT_ID>/<REGISTRY_NAME>/gymnasium-env:1.0.0'
