steps:
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'build', '-t', 'us-docker.pkg.dev/akvelon-gke-aieco/agent-sandbox-dima/gymnasium-env:1.0.2', '.' ]
images:
- 'us-docker.pkg.dev/akvelon-gke-aieco/agent-sandbox-dima/gymnasium-env:1.0.2'
