#!/usr/bin/env python3
# Copyright 2025 The Kubernetes Authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

import os
import argparse
import shutil
import sys
import subprocess

from shared import utils

repo_root = utils.get_repo_root()
if repo_root not in sys.path:
    sys.path.insert(0, repo_root)
    
from dev.tools.shared import utils as tools_utils

def main(args):
    """ invokes e2e tests in kind cluster and outputs a junit report in the ARTIFACTS dir

    The ARTIFACTS environment variable is set by prow.
    """
    image_tag = tools_utils.get_image_tag()
    result = subprocess.run([f"{repo_root}/dev/tools/create-kind-cluster", "e2e-test", "--recreate", "--kubeconfig", f"{repo_root}/bin/KUBECONFIG"])
    if result.returncode != 0:
        return result.returncode
    result = subprocess.run([f"{repo_root}/dev/tools/push-images", "--kind-cluster-name", "e2e-test", "--image-prefix", args.image_prefix, "--image-tag", image_tag])
    if result.returncode != 0:
        return result.returncode
    result = subprocess.run([f"{repo_root}/dev/tools/deploy-to-kube", "--image-prefix", args.image_prefix, "--image-tag", image_tag])
    if result.returncode != 0:
        return result.returncode
    result = subprocess.run([f"{repo_root}/dev/tools/deploy-cloud-provider"])
    if result.returncode != 0:
        return result.returncode
    result = subprocess.run([f"{repo_root}/dev/tools/test-e2e", "--image-prefix", args.image_prefix, "--suite", args.suite])

    # Always create junit file whether tests pass or fail
    artifact_dir = os.getenv("ARTIFACTS")
    if artifact_dir:
        shutil.copy(f"{repo_root}/bin/e2e-go-junit.xml", f"{artifact_dir}/junit_go.xml")
        shutil.copy(f"{repo_root}/bin/e2e-python-sdk-junit.xml", f"{artifact_dir}/junit_python_sdk.xml")

    return result.returncode


if __name__ == "__main__":
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--image-prefix",
        dest="image_prefix",
        help="prefix for the image name. requires slash at the end if a path",
        type=str,
        default="kind.local/",
    )
    parser.add_argument(
        "--suite",
        dest="suite",
        help="which suite of tests to run",
        type=str,
        choices=["all", "tests", "benchmarks"],
        default="all",
    )
    args = parser.parse_args()
    sys.exit(main(args))
