#!/usr/bin/env python3
# Copyright 2025 The Kubernetes Authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

import os
import shutil
import sys
import subprocess

from shared import utils


def main():
    """ invokes e2e tests in kind cluster and outputs a junit report in the ARTIFACTS dir

    The ARTIFACTS environment variable is set by prow.
    """
    repo_root = utils.get_repo_root()

    result = subprocess.run([f"{repo_root}/dev/tools/create-kind-cluster", "e2e-test", "--recreate", "--kubeconfig", f"{repo_root}/bin/KUBECONFIG"])
    if result.returncode != 0:
        return result.returncode
    result = subprocess.run([f"{repo_root}/dev/tools/push-images", "--kind-cluster-name", "e2e-test", "--image-prefix", "kind.local/"])
    if result.returncode != 0:
        return result.returncode
    result = subprocess.run([f"{repo_root}/dev/tools/deploy-to-kube", "--image-prefix", "kind.local/"])
    if result.returncode != 0:
        return result.returncode
    result = subprocess.run([f"{repo_root}/dev/tools/deploy-cloud-provider"])
    if result.returncode != 0:
        return result.returncode
    result = subprocess.run([f"{repo_root}/dev/tools/test-e2e", "--image-prefix", "kind.local/"])

    # Always create junit file whether tests pass or fail
    artifact_dir = os.getenv("ARTIFACTS")
    if artifact_dir:
        shutil.copy(f"{repo_root}/bin/e2e-go-junit.xml", f"{artifact_dir}/junit_go.xml")
        shutil.copy(f"{repo_root}/bin/e2e-python-sdk-junit.xml", f"{artifact_dir}/junit_python_sdk.xml")

    return result.returncode


if __name__ == "__main__":
    sys.exit(main())
