version: "2"
linters:
  enable:
    - depguard
    - exptostd
    - godot
    - iface
    - importas
    - iotamixing
    - modernize
    - nilnesserr
    - recvcheck
    - revive
    - sloglint
    - testifylint
    - unconvert
    - govet
    - staticcheck
    - unparam
    - misspell
    - errcheck
    - ineffassign
  settings:
    depguard:
      rules:
        forbid-pkg-errors:
          deny:
            - pkg: sort
              desc: Should be replaced with slices package
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    paths:
      - third_party$
      - builtin$
      - examples$
    rules:
      - linters:
          - staticcheck
        text: "QF1008"
formatters:
  enable:
    - gofmt
    - goimports
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
