#!/usr/bin/env python3
# Copyright 2025 The Kubernetes Authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

import argparse
import os
import subprocess

from shared import utils


def create_buildx_builder_if_not_exists():
    builder_name = "agent-sandbox-builder"
    try:
        subprocess.run(
            ["docker", "buildx", "inspect", builder_name],
            check=True,
            capture_output=True,
            text=True,
        )
        print(f"buildx builder '{builder_name}' already exists.")
    except subprocess.CalledProcessError:
        print(f"creating buildx builder '{builder_name}'.")
        subprocess.run(
            ["docker", "buildx", "create", "--name", builder_name], check=True
        )
    subprocess.run(["docker", "buildx", "use", builder_name], check=True)


def build_and_push_image_with_docker_buildx(args, service_name, srcdir, dockerfile_path):
    platforms = "linux/amd64,linux/arm64"
    build_cmd = [
        "docker",
        "buildx",
        "build",
        "--progress=plain",
        f"--output=type={args.docker_build_output_type}",
    ]
    if args.docker_build_output_type == "registry":
        build_cmd.append("--platform=" + platforms)
    image_name = utils.get_full_image_name(args, service_name)
    build_cmd.extend(["-t", image_name])
    for tag in args.extra_image_tags:  # additional image tags
        extra_tag = utils.get_full_image_name(args, service_name, tag=tag)
        build_cmd.extend(["-t", extra_tag])
    build_cmd.extend([
        "-f",
        os.path.basename(dockerfile_path),
        ".",
    ])
    subprocess.run(build_cmd, cwd=srcdir, check=True)
    print(f"pushed image {image_name}")


def load_kind_image(cluster_name, service_name, srcdir):
    image_name = utils.get_full_image_name(args, service_name)
    build_cmd = [
        "kind",
        "load",
        "docker-image",
        f"--name={cluster_name}",
        image_name,
    ]

    subprocess.run(build_cmd, cwd=srcdir, check=True)
    print(f"loaded image {image_name} into kind cluster {args.kind_cluster_name}")


def build_and_push_image(args, service_name, srcdir, dockerfile_path):
    build_and_push_image_with_docker_buildx(args, service_name, srcdir, dockerfile_path)
    if args.kind_cluster_name:
        load_kind_image(args.kind_cluster_name, service_name, srcdir)


def main(args):
    """Builds and pushes all discovered Docker images."""
    excluded_dirs = {"bin", "dev", "docs", "k8s", "site",
                     "temp", "tests", "tmp", ".venv"}

    if args.controller_only:
        # TODO: Implement an explicit inclusion strategy for controller only Dockerfile.
        excluded_dirs.update({"examples", "clients"})

    for root, dirs, files in os.walk(".", topdown=True):
        dirs[:] = [d for d in dirs if d not in excluded_dirs]

        if "Dockerfile" in files:
            dockerfile_path = os.path.join(root, "Dockerfile")
            context_dir = root
            service_name = os.path.basename(root)  # same as image name

            if not service_name:
                continue

            if service_name == ".":
                service_name = "agent-sandbox-controller"

            print(f"--- Found Dockerfile at: {dockerfile_path}")
            print(f"--- Service Name: {service_name}")
            print(f"--- Context Dir: {context_dir}")

            print(f"create Docker buildx builder for {service_name}")
            create_buildx_builder_if_not_exists()
            print(f"building image for {service_name}")
            build_and_push_image(args, service_name, context_dir, dockerfile_path)
            # TODO: Handle duplicate service names in different paths


if __name__ == "__main__":
    # parse arguments and call
    parser = argparse.ArgumentParser(description="Build and push Docker images")
    parser.add_argument("--image-prefix",
                        dest="image_prefix",
                        help="Prefix for the image name. requires slash at the end if a path",
                        type=str,
                        default=os.getenv("IMAGE_PREFIX"))
    parser.add_argument("--extra-image-tag",
                        dest="extra_image_tags",
                        help="Additional tags to use when publishing images.",
                        type=str,
                        action="append",
                        default=[])
    parser.add_argument("--kind-cluster-name",
                        dest="kind_cluster_name",
                        help="Name of the kind cluster. If set, images will be loaded into the cluster",
                        type=str,
                        default=os.getenv("KIND_CLUSTER_NAME"))
    parser.add_argument("--controller-only",
                        dest="controller_only",
                        action="store_true",
                        help="Only build and push the agent-sandbox-controller image.")
    args = parser.parse_args()

    if args.kind_cluster_name:
        args.docker_build_output_type = "docker"
    else:
        args.docker_build_output_type = "registry"

    main(args)
