#!/usr/bin/env python3
# Copyright 2025 The Kubernetes Authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

import subprocess
import sys

from shared import utils


def main():
    """ invokes unit tests and outputs a junit results file """
    repo_root = utils.get_repo_root()

    result = subprocess.run(["make", "deploy-kind"], cwd=repo_root)
    if result.returncode != 0:
        return result.returncode

    result = subprocess.run(utils.go_tool_args(
        "gotestsum", f"--junitfile={repo_root}/bin/e2e-junit.xml",
        "--", "./test/e2e/...", "--parallel=1"
    ), cwd=repo_root)
    return result.returncode


if __name__ == "__main__":
    sys.exit(main())
