apiVersion: extensions.agents.x-k8s.io/v1alpha1
kind: SandboxTemplate
metadata:
  # The test_client.py expects the template to have this name
  name: python-sandbox-template
  namespace: default
spec:
  podTemplate:
    spec:
      # Optional, if gVisor is specified, must have gVisor enabled node
      runtimeClassName: gvisor
      containers:
      - name: python-runtime
        # The test_client.py expects the image to be agent-sandbox/examples/python-runtime-sandbox
        image: us-central1-docker.pkg.dev/k8s-staging-images/agent-sandbox/python-runtime-sandbox:latest-main
        ports:
        - containerPort: 8888
        readinessProbe:
          httpGet:
            path: "/"
            port: 8888
          initialDelaySeconds: 0
          periodSeconds: 1
        livenessProbe:
          httpGet:
            path: "/"
            port: 8888
          initialDelaySeconds: 2
          periodSeconds: 10
        resources:
          requests:
            cpu: "250m"
            memory: "512Mi"
            ephemeral-storage: "512Mi"
      restartPolicy: "OnFailure"
