apiVersion: v1
kind: Service
metadata:
  name: python-sandbox-service
  namespace: default
spec:
  type: ClusterIP
  selector:
    sandbox: my-python-sandbox
  ports:
    - protocol: TCP
      port: 8888
      targetPort: 8888
