name: MCP Server CI

on:
  pull_request:
    paths:
      - "clients/integrations/mcp-server/**"
      - ".github/workflows/mcp-server-ci.yml"
  push:
    branches:
      - "add-mcp-server-test"
    paths:
      - "clients/integrations/mcp-server/**"
      - ".github/workflows/mcp-server-ci.yml"

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  unittest:
    name: Run Unit Tests 🧪
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10", "3.13"]
    defaults:
      run:
        working-directory: clients/integrations/mcp-server

    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3

      - name: Set up Python
        uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405 # v6.2.0
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies (including tests)
        run: python3 -m pip install ".[test]"

      - name: Run Unit Tests
        run: python3 -m pytest
